### ISSUE TITLE
Idea sketch : sort out haskell-ide-engine BIOS

### ISSUE THREAD

**Issue by alanz** [haskell-org/summer-of-haskell#86]
See https://github.com/haskell/haskell-ide-engine/issues/1053

**Comment by gwils** [comment]
I'd love to see more HIE work come out of GSOC.

Since you have options for the BIOS going forward but don't know which is best, perhaps the GSOC idea could be a comparison? The student could spend some time evaluating the benefits and required work for each of the three options and then provide a proof-of-concept or partial implementation of the chosen approach.

**Comment by jaspervdj** [comment]
I would also very much like to have at least one HIE project.  I think we should require at least a partial implementation of one of the three from the student.

**Comment by alanz** [comment]
I think the most likely HIE project would be to integrate the new (GHC 8.8) .hie files via LSIF.  Or even just bring LSIF into hie, so that converters can be made to generate them.

**Comment by jaspervdj** [comment]
Closing this to clean up for GSoC 2020.
